### ISSUE TITLE
Scrub credentials from the project

### ISSUE THREAD

**Issue by mediumTaj** [ibmets/rainbow-octopus#1]
It would be a good idea to scrub credentials from this project. https://github.com/ibmets/rainbow-octopus/blob/master/RainbowOctopus/Assets/RainbowOctopus/Scripts/ConversationHandler.cs#L50-L53

Not sure if there are more instances of this.

**Comment by kevinxbrown** [comment]
Thank you - these are old - but I have removed the credentials, and replaced with xxx. Many thanks for raising the issue.
